import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Coordinates around Lat 13.8799, Lng 100.6140 (Bangkok suburb)
const RESTAURANTS = [
  {
    placeId: "seed-bkk-001",
    name: "Lat Phrao Cafe",
    address: "99 Lat Phrao Rd, Bangkok",
    lat: 13.8812,
    lng: 100.6121,
    rating: 4.5,
    priceLevel: 2,
    userRatingsTotal: 120,
  },
  {
    placeId: "seed-bkk-002",
    name: "Ratchada Street Food",
    address: "12 Soi Lat Phrao 23, Bangkok",
    lat: 13.8845,
    lng: 100.6178,
    rating: 4.3,
    priceLevel: 1,
    userRatingsTotal: 340,
  },
  {
    placeId: "seed-bkk-003",
    name: "Central Plaza Bistro",
    address: "Central Plaza Ladprao, Bangkok",
    lat: 13.8164,
    lng: 100.5617,
    rating: 4.1,
    priceLevel: 3,
    userRatingsTotal: 520,
  },
  {
    placeId: "seed-bkk-004",
    name: "Chatuchak Garden Eatery",
    address: "1 Kamphaeng Phet 2 Rd, Bangkok",
    lat: 13.8249,
    lng: 100.5503,
    rating: 4.6,
    priceLevel: 2,
    userRatingsTotal: 210,
  },
  {
    placeId: "seed-bkk-005",
    name: "Phahon Yothin Noodle House",
    address: "56 Phahon Yothin Rd, Bangkok",
    lat: 13.8661,
    lng: 100.5942,
    rating: 4.7,
    priceLevel: 1,
    userRatingsTotal: 150,
  },
  {
    placeId: "seed-bkk-006",
    name: "Union Mall Diner",
    address: "Union Mall, Bangkok",
    lat: 13.8123,
    lng: 100.5612,
    rating: 4.2,
    priceLevel: 2,
    userRatingsTotal: 95,
  },
  {
    placeId: "seed-bkk-007",
    name: "Kaset Nawamin BBQ",
    address: "Kaset Nawamin Rd, Bangkok",
    lat: 13.8702,
    lng: 100.6156,
    rating: 4.4,
    priceLevel: 2,
    userRatingsTotal: 270,
  },
  {
    placeId: "seed-bkk-008",
    name: "Major Avenue Bistro",
    address: "Major Ratchayothin, Bangkok",
    lat: 13.8283,
    lng: 100.5689,
    rating: 4.0,
    priceLevel: 2,
    userRatingsTotal: 180,
  },
  {
    placeId: "seed-bkk-009",
    name: "Pracha Chuen Steak House",
    address: "Pracha Chuen Rd, Bangkok",
    lat: 13.8534,
    lng: 100.5537,
    rating: 4.5,
    priceLevel: 3,
    userRatingsTotal: 88,
  },
  {
    placeId: "seed-bkk-010",
    name: "Kasetsart Night Market Food",
    address: "50 Ngamwongwan Rd, Bangkok",
    lat: 13.8485,
    lng: 100.5714,
    rating: 4.6,
    priceLevel: 1,
    userRatingsTotal: 430,
  },
  {
    placeId: "seed-bkk-011",
    name: "Vibhavadi Organic Kitchen",
    address: "Vibhavadi Rangsit Rd, Bangkok",
    lat: 13.8577,
    lng: 100.5802,
    rating: 4.8,
    priceLevel: 3,
    userRatingsTotal: 205,
  },
  {
    placeId: "seed-bkk-012",
    name: "Ramintra Fusion Bar",
    address: "Ramintra Rd, Bangkok",
    lat: 13.8709,
    lng: 100.6344,
    rating: 4.3,
    priceLevel: 2,
    userRatingsTotal: 130,
  },
  {
    placeId: "seed-bkk-013",
    name: "Lat Phrao Soi 1 Grill",
    address: "Lat Phrao Soi 1, Bangkok",
    lat: 13.8801,
    lng: 100.6075,
    rating: 4.2,
    priceLevel: 2,
    userRatingsTotal: 165,
  },
  {
    placeId: "seed-bkk-014",
    name: "Sena Nikhom Dessert Lab",
    address: "Sena Nikhom Rd, Bangkok",
    lat: 13.8648,
    lng: 100.5963,
    rating: 4.8,
    priceLevel: 1,
    userRatingsTotal: 220,
  },
  {
    placeId: "seed-bkk-015",
    name: "Green Line Vegan Kitchen",
    address: "Phahon Yothin 34, Bangkok",
    lat: 13.879,
    lng: 100.6021,
    rating: 4.6,
    priceLevel: 2,
    userRatingsTotal: 98,
  },
  {
    placeId: "seed-bkk-016",
    name: "Chandara Boat Noodles",
    address: "Kaset Intersection, Bangkok",
    lat: 13.8652,
    lng: 100.6143,
    rating: 4.4,
    priceLevel: 1,
    userRatingsTotal: 310,
  },
  {
    placeId: "seed-bkk-017",
    name: "Pradit Manutham Tapas Bar",
    address: "Pradit Manutham Rd, Bangkok",
    lat: 13.8706,
    lng: 100.6265,
    rating: 4.5,
    priceLevel: 3,
    userRatingsTotal: 140,
  },
  {
    placeId: "seed-bkk-018",
    name: "Sutthisan Izakaya",
    address: "Sutthisan Rd, Bangkok",
    lat: 13.8013,
    lng: 100.5711,
    rating: 4.3,
    priceLevel: 2,
    userRatingsTotal: 255,
  },
  {
    placeId: "seed-bkk-019",
    name: "Chan Kaset Bistro",
    address: "Phahon Yothin 45, Bangkok",
    lat: 13.8954,
    lng: 100.5979,
    rating: 4.7,
    priceLevel: 3,
    userRatingsTotal: 175,
  },
  {
    placeId: "seed-bkk-020",
    name: "Sena Fest Seafood",
    address: "Sena Village, Bangkok",
    lat: 13.8932,
    lng: 100.6115,
    rating: 4.1,
    priceLevel: 2,
    userRatingsTotal: 260,
  },
  {
    placeId: "seed-bkk-021",
    name: "Lat Phrao Night Roast",
    address: "Lat Phrao 71, Bangkok",
    lat: 13.8242,
    lng: 100.6208,
    rating: 4.5,
    priceLevel: 2,
    userRatingsTotal: 112,
  },
  {
    placeId: "seed-bkk-022",
    name: "Kaset Smart Cafe",
    address: "Ngamwongwan 1, Bangkok",
    lat: 13.8433,
    lng: 100.5891,
    rating: 4.9,
    priceLevel: 2,
    userRatingsTotal: 240,
  },
  {
    placeId: "seed-bkk-023",
    name: "Viphawadee Claypot Rice",
    address: "Vibhavadi 60, Bangkok",
    lat: 13.8742,
    lng: 100.5848,
    rating: 4.4,
    priceLevel: 1,
    userRatingsTotal: 185,
  },
  {
    placeId: "seed-bkk-024",
    name: "Prasert-Manuk Market Snacks",
    address: "Prasert-Manuk Rd, Bangkok",
    lat: 13.8895,
    lng: 100.6057,
    rating: 4.2,
    priceLevel: 1,
    userRatingsTotal: 320,
  },
];

async function main() {
  let upserted = 0;
  for (const r of RESTAURANTS) {
    await prisma.restaurant.upsert({
      where: { placeId: r.placeId },
      update: {
        name: r.name,
        address: r.address,
        lat: r.lat,
        lng: r.lng,
        rating: r.rating,
        priceLevel: r.priceLevel,
        userRatingsTotal: r.userRatingsTotal,
        source: "seed",
        fetchedAt: new Date(),
      },
      create: {
        ...r,
        source: "seed",
        fetchedAt: new Date(),
      },
    });
    upserted += 1;
  }
  console.log(`Seeded ${upserted} restaurants near Lat 13.88 / Lng 100.61`);
}

main()
  .catch((err) => {
    console.error("Seed failed:", err);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
